name: Generate contributions GIF

on:
  schedule: # execute every 12 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Job to generate contributions GIF
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
  
        with:
          github_user_name: karthikmurali60
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
